### PR TITLE
Fix for Linux file descriptor limits by loading file chunks in sets o…

### PR DESCRIPTION
**Pull request by J-Rojas**
…f 1000.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
i become this error: Failed with status code: 200

**Comment by J-Rojas** [comment]
Please post the output of your console.

**Comment by LinuxDonald** [comment]
linuxdonald@linuxdonald-desktop:~$ ue4-mp-downloader
prompt: username:
prompt: password:

Failed with status code: 200
linuxdonald@linuxdonald-desktop:~$ 

Is it maybe an problem because i have two-factor-auth activated?

**Comment by J-Rojas** [comment]
Not sure.

I'm assuming this problem is not in my branch, but in the master branch, since I didn't change any of the authentication code. Did you have the same problem there?

If so, then please file a bug report. The PR comments are for discussing the code changes that are being merged.

**Comment by LinuxDonald** [comment]
Im getting this error with your pr:

`Getting item build info.
Getting item manifest.
/usr/local/lib/node_modules/ue4-mp-downloader/epic_api.js:648
	var chunk_path = buildinfo.items.CHUNKS['path'];
	                                 ^

TypeError: Cannot read property 'CHUNKS' of undefined
    at epic_api.BuildItemChunkListFromManifest (/usr/local/lib/node_modules/ue4-mp-downloader/epic_api.js:648:35)
    at global.epic_api.GetItemManifest (/usr/local/lib/node_modules/ue4-mp-downloader/downloader.js:141:38)
    at Request._callback (/usr/local/lib/node_modules/ue4-mp-downloader/epic_api.js:558:5)
    at Request.self.callback (/usr/local/lib/node_modules/ue4-mp-downloader/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/ue4-mp-downloader/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ue4-mp-downloader/node_modules/request/request.js:1079:12)
`

**Pull request merged**
